"""user add token

Revision ID: 02ec4e91e634
Revises: 
Create Date: 2020-10-06 22:04:22.538304

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02ec4e91e634'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('token', sa.String(length=64), nullable=True))
    op.add_column('user', sa.Column('token_expiretion', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_user_token'), 'user', ['token'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_token'), table_name='user')
    op.drop_column('user', 'token_expiretion')
    op.drop_column('user', 'token')
    # ### end Alembic commands ###
